work/app/bitovka/urls.py
from django.urls import path
from django.contrib import admin
from catalog.models import Bitovka
from bitovka import views
from bitovka.models import *

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import render
from django.views.generic import DetailView


urlpatterns = [
         path(r'', views.catalog, name = 'catalog'),
         path(r'<int:pk>',DetailView.as_view(model =Bitovka, template_name = "1_obiect.html"), name = 'bitovka_detail')
    ]\
            + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
            + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

work/work/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import render


def main(request):
    return render(request, "main.html")

def contact(request):
    return render(request, "contact.html")

def garantii(request):
    return render(request, "garantia.html")

def compania(request):
    return render(request, "Company.html")

def dostavka(request):
    return render(request, "dostavka.html")






urlpatterns = [
    path(r'universal-stroyspb/admin/', admin.site.urls),
    path(r'universal-stroyspb/bitovki/', include('app.bitovka.urls'), name = "bitovka"),
    path(r'universal-stroyspb/bitovki/',include('app.bitovka.urls'), name = 'bitovka_detail'),
    path(r'universal-stroyspb/conteineri/', include('app.continer.urls'), name = "coteiner"),
    path(r'universal-stroyspb/conteineri/', include('app.continer.urls'), name = "coteiner_detail"),
    path(r'', include('app.StrSec.urls'), name = "modul"),
    path(r'', include('app.StrSec.urls'), name = "modulstr_detail"),
    path(r'universal-stroyspb/postsec/', include('app.StrSec.urls'), name = "postsec"),
    path(r'universal-stroyspb/postsec/', include('app.StrSec.urls'), name = "postsec_detail"),
    path(r'', include('app.by.urls'), name = 'base'),
    path(r'universal-stroyspb/contaсts/', contact, name = 'contacts'),
    path(r'universal-stroyspb/garantii/', garantii, name = 'garantii'),
    path(r'universal-stroyspb/compania/', compania, name = 'compania'),
    path(r'universal-stroyspb/dostavka/', dostavka, name = 'dostavka'),
    path(r'universal-stroyspb/work/', include('app.our_work.urls')),
    path(r'universal-stroyspb/work/', include('app.our_work.urls') , name = "work_detail"),
    path(r'universal-stroyspb/bani/', include('app.bani.urls'), name = 'bani' ),
    path(r'universal-stroyspb/sale/', include('app.by.urls')),
    path(r'universal-stroyspb/arenda/', include('app.arenda.urls')),
    path(r'universal-stroyspb/arenda/', include('app.arenda.urls'), name = "arenda_detail"),
    path(r'universal-stroyspb/sale/', include('app.by.urls'), name = "1_by"),
    path(r'universal-stroyspb/news/', include('app.news.urls'), name = "news_detail"),
    path(r'universal-stroyspb/news/', include('app.news.urls'))

]\
            + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
            + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

work/app/bitovka/models.py
from django.db import models
from catalog.models import Bitovka


class PriceBitovka(models.Model):
	name = models.ForeignKey(Bitovka, blank = True, null = True, default = True, on_delete = models.CASCADE)
	size = models.CharField(max_length = 50)
	price_dvp = models.DecimalField(max_digits = 7, decimal_places = 0)
	price_vagonka = models.DecimalField(max_digits = 7, decimal_places = 0)

	def __str__(self):
		return "%s, %s" % (self.name, self.size)

	class Meta:
		verbose_name = "Размер и цены бытовок"
		verbose_name_plural = "Размеры и цены бытовок"


class ImgBitovka(models.Model):
	name = models.ForeignKey(Bitovka, blank = True, null = True, default = True, on_delete = models.CASCADE)
	image = models.ImageField(upload_to = "product images/")
	is_active = models.BooleanField(default = False)
	is_main = models.BooleanField(default = False)

	def __str__(self):
		return "%s" % self.name

	class Meta:
		verbose_name = "Фотграфия бытовок"
		verbose_name_plural = "Фотографии  бытовок"


class CharacteristicBitovka(models.Model):
	name = models.ForeignKey(Bitovka, blank = True, null = True, default = True, on_delete = models.CASCADE)
	title = models.CharField(max_length = 50)
	description = models.CharField(max_length = 250)

	def __str__(self):
		return "%s" % self.name

	class Meta():
		verbose_name = "Характеристика бытовок"
		verbose_name_plural = "Характеристики бытовок"

work/app/continer/models.py
from django.db import models
from catalog.models import BlockConteiner


class PriceConteiner(models.Model):
	name = models.ForeignKey(BlockConteiner, blank = True, null = True, default = True, on_delete = models.CASCADE)
	size = models.CharField(max_length = 50)
	price_dvp = models.DecimalField(max_digits = 7, decimal_places = 0)
	price_pvx = models.DecimalField(max_digits = 7, decimal_places = 0)
	price_vagonka = models.DecimalField(max_digits = 7, decimal_places = 0)
	price_mdf = models.DecimalField(max_digits = 7, decimal_places = 0)
	price_LDCP = models.DecimalField(max_digits = 7, decimal_places = 0)

	def __str__(self):
		return "%s, %s" % (self.name, self.size)

	class Meta:
		verbose_name = "Размер и цены контейнера"
		verbose_name_plural = "Размеры и цены контейнера"


class ImgConteiner(models.Model):
	name = models.ForeignKey(BlockConteiner, blank = True, null = True, default = True, on_delete = models.CASCADE)
	image = models.ImageField(upload_to = "product images/")
	is_active = models.BooleanField(default = False)
	is_main = models.BooleanField(default = False)

	def __str__(self):
		return "%s" % self.name

	class Meta:
		verbose_name = "Фотграфия контейнеров"
		verbose_name_plural = "Фотографии  контейнеров"

class CharacteristicConteiner(models.Model):
	name = models.ForeignKey(BlockConteiner, blank = True, null = True, default = True, on_delete = models.CASCADE)
	title = models.CharField(max_length = 50)
	description = models.CharField(max_length = 250)
	def __str__(self):
		return "%s" % self.name

	class Meta:
		verbose_name = "Характеристика контейнеров"
		verbose_name_plural = "Характеристики  контейнеров"

work/app/bitovka/views.py
from django.shortcuts import render
from .models import *
from catalog.models import *
from by.models import *

def catalog(request):
	products = Bitovka.objects.all()

	raspashonka_5 = PriceBitovka.objects.filter(size = "5.0х2.3",  name = "4")
	raspashonka_6 = PriceBitovka.objects.filter(size = "6.0х2.3",  name = "4")
	raspashonka_7 = PriceBitovka.objects.filter(size = "7.0х2.3",  name = "4")
	raspashonka_img = ImgBitovka.objects.filter(name = "4")

	torcevaya_tamb_5 = PriceBitovka.objects.filter(size = "5.0х2.3",  name = "3")
	torcevaya_tamb_6 = PriceBitovka.objects.filter(size = "6.0х2.3",  name = "3")
	torcevaya_tamb_7 = PriceBitovka.objects.filter(size = "7.0х2.3",  name = "3")
	torcevaya_tamb_img = ImgBitovka.objects.filter(name = "3")

	fasadnaya_5 = PriceBitovka.objects.filter(size = "5.0х2.3",  name = "2")
	fasadnaya_6 = PriceBitovka.objects.filter(size = "6.0х2.3",  name = "2")
	fasadnaya_7 = PriceBitovka.objects.filter(size = "7.0х2.3",  name = "2")
	fasadnaya_img = ImgBitovka.objects.filter(name = "2")

	torcevaya_4 = PriceBitovka.objects.filter(size = "4.0х2.3",  name = "1")
	torcevaya_5 = PriceBitovka.objects.filter(size = "5.0х2.3",  name = "1")
	torcevaya_6 = PriceBitovka.objects.filter(size = "6.0х2.3",  name = "1")
	torcevaya_img = ImgBitovka.objects.filter(name = "1")



	by_img = ImgBy.objects.filter(is_active = True)
	return render(request, "bitovka.html", locals())

work/templates/1_obiect.html
{% extends "base.html" %}

{%  block content %}
{% load static %}
<div class = "product_main_1">
    <h2 class = "name_product">{{bitovka.name}}</h2>
    <div class = "foto_producta">
        {%for image in bitovka.imgbitovka_set.all%}
        <img src=  "{{image.image}}" class = " product_image_one">
        {%endfor%}
            <a class="prev_pr prev_pr_1_ob" onclick=" plusSlide_Pr_ob(-1)">&#10094</a>
            <a class="next_pr next_pr_1_ob" onclick=" plusSlide_Pr_ob(+1)">&#10095</a>
        <div>
        {%for image in bitovka.imgbitovka_set.all%}
            <span class = dot_pr_ob></span>
        {% endfor %}
        </div>
    </div>
    <div class = "info">
        <p>Производство: завод Универсал-Строй, Санкт-Петербург. Размеры: 3.0x2.3 метра.</p>
        <p> Внутренняя отделка: Оргалит, ДВП.</p>
        <p> Цены указаны с доставкой под кран покупателя: г. Санкт-Петербург и включают НДС.</p>
        <p> Доставка с разгрузкой манипулятором/доставка в регионы смотрите раздел Доставка.</p>
        <p>Размер:</p>
        <div>
            {%for price in bitovka.pricebitovka_set.all%}
            <label >
            <input class="product_int" type="radio" name="size_ob" value="{{price.price_dvp}}" checked/>
            <span class="product_size">{{price.size}}</span>
            </label>
            {%endfor%}
        </div>
        <p> Материал</p>
        <div class="flex">
                <label >
                    <input  type="radio" name="mat_ob" value="0" checked/>
                    <span>
                        <img src= "{%static 'img/mt1.jpg' %}" class="mat_img mat_img_ob">
                        <p class = "mat">Двп</p>
                </span>
                </label>
                <label >
                    <input  type="radio" name="mat_ob" value="0.1" />
                    <span>
                        <img src= "{%static 'img/mt3.jpg' %}" class="mat_img mat_img_ob" >
                        <p class = "mat">Вагонка</p>
                    </span>
                </label>
        </div>
                <div class = "zakaz_price">
                <div class="price price_obiect" id = "price_ob"></div>
                <div class="product_btn"> Заказать</div>
            </div>
        </div>
    <div class = "dop_complect">Дополнительная комплектация</div>
    <div class = menu_complect>
        <div class = "dother_comlect">
            <input class = "dop_input_price" name = "dop_price_1" type="radio" value="15000" checked/>
            <p class = "dop_name dop_name_1"   name = "dop_name_1" value = "15000">Металлическая утепленная дверь с замком (Россия) : 15000р.</p>
            <input class = "dop_input" name = "dop_int_1" type="text" value="0">
        </div>  
        <div class = "dother_comlect">
            <input class = "dop_input_price" name = "dop_price_2" type="radio" value="6500" checked/>
            <p class = "dop_name" name = "dop_name_2" value = 6500>Окно ПВХ поворотно-откидное 900х1000 мм : 6500р.</p>
            <input class = "dop_input" name = "dop_int_2" type="text" value="0">
        </div>
        <div class = "dother_comlect">
            <input class = "dop_input_price" name = "dop_price_3" type="radio" value="5500" checked/>
            <p class = "dop_name" name = "dop_name_3" value = 6500>Окно ПВХ глухое 900х1000 мм : 5500р.</p>
            <input class = "dop_input"  name = "dop_int_3" type="text" value="0">
        </div>
        <div class = "dother_comlect">
            <input class = "dop_input_price" name = "dop_price_4" type="radio" value="5000" checked/>
            <p class = "dop_name"  name = "dop_name_4" value = 6500>Пластиковые стеклопакеты(однокамерные), М/кв : 5000р.</p>
            <input class = "dop_input"  name = "dop_int_4" type="text" value="0">
        </div>
        <div class = "dother_comlect">
            <input class = "dop_input_price" name = "dop_price_5" type="radio" value="2500" checked/>
            <p class = "dop_name" name = "dop_name_5" value = 6500>Решетка на окно : 2500р.</p>
            <input class = "dop_input"  name = "dop_int_5" type="text" value="0">
        </div>
    </div>

</div>
<script src="{% static 'js/foto_obiecta.js' %}"></script>
{% endblock %}

work/templates/2_obiect.html
{% extends "base.html" %}

{%  block content %}
{% load static %}
<div class = "product_main_1">
    <h2 class = "name_product">{{blockconteiner.name}}</h2>
    <div class = "foto_producta">
        {%for image in blockconteiner.imgconteiner_set.all%}
        <img src=  "{{image.image}}" class = " product_image_one">
        {%endfor%}
            <a class="prev_pr prev_pr_1_ob" onclick=" plusSlide_Pr_ob(-1)">&#10094</a>
            <a class="next_pr next_pr_1_ob" onclick=" plusSlide_Pr_ob(+1)">&#10095</a>
        <div>
        {%for image in blockconteiner.imgbitovka_set.all%}
            <span class = dot_pr_ob></span>
        {% endfor %}
        </div>
    </div>
    <div class = "info">
        <p>Производство: завод Универсал-Строй, Санкт-Петербург</p>
        <p> Цены указаны с доставкой под кран покупателя: г. Санкт-Петербург и включают НДС.</p>
        <p> Доставка с разгрузкой манипулятором/доставка в регионы смотрите раздел Доставка.</p>
        <p>Размер:</p>
        <div>
            {%for price in blockconteiner.priceconteiner_set.all%}
            <label >
            <input class="product_int" type="radio" name="size_ob_1" value="{{price.price_dvp}}" checked/>
            <span class="product_size">{{price.size}}</span>
            </label>
            {%endfor%}
        </div>
        <p> Материал</p>
        <div class="flex">
                <label >
                    <input  type="radio" name="mat_ob_1" value="0" checked/>
                    <span>
                        <img src= "{%static 'img/mt1.jpg' %}" class="mat_img mat_img_ob">
                        <p class = "mat">Двп</p>
                </span>
                </label>
                <label >
                    <input  type="radio" name="mat_ob_1" value="0.1" />
                    <span>
                        <img src= "{%static 'img/mt3.jpg' %}" class="mat_img mat_img_ob" >
                        <p class = "mat">Вагонка</p>
                    </span>
                </label>
        </div>
                <div class = "zakaz_price">
                <div class="price price_obiect" id = "price_ob_1"></div>
                <div class="product_btn"> Заказать</div>
            </div>
        </div>
    <div class = "dop_complect">Дополнительная комплектация</div>
    <div class = menu_complect>
        <div class = "dother_comlect">
            <input class = "dop_input_price" name = "dop_price_1" type="radio" value="15000" checked/>
            <p class = "dop_name dop_name_1"   name = "dop_name_1" value = "15000">Металлическая утепленная дверь с замком (Россия) : 15000р.</p>
            <input class = "dop_input" name = "dop_int_1" type="text" value="0">
        </div>
        <div class = "dother_comlect">
            <input class = "dop_input_price" name = "dop_price_2" type="radio" value="6500" checked/>
            <p class = "dop_name" name = "dop_name_2" value = 6500>Окно ПВХ поворотно-откидное 900х1000 мм : 6500р.</p>
            <input class = "dop_input" name = "dop_int_2" type="text" value="0">
        </div>
        <div class = "dother_comlect">
            <input class = "dop_input_price" name = "dop_price_3" type="radio" value="5500" checked/>
            <p class = "dop_name" name = "dop_name_3" value = 6500>Окно ПВХ глухое 900х1000 мм : 5500р.</p>
            <input class = "dop_input"  name = "dop_int_3" type="text" value="0">
        </div>
        <div class = "dother_comlect">
            <input class = "dop_input_price" name = "dop_price_4" type="radio" value="5000" checked/>
            <p class = "dop_name"  name = "dop_name_4" value = 6500>Пластиковые стеклопакеты(однокамерные), М/кв : 5000р.</p>
            <input class = "dop_input"  name = "dop_int_4" type="text" value="0">
        </div>
        <div class = "dother_comlect">
            <input class = "dop_input_price" name = "dop_price_5" type="radio" value="2500" checked/>
            <p class = "dop_name" name = "dop_name_5" value = 6500>Решетка на окно : 2500р.</p>
            <input class = "dop_input"  name = "dop_int_5" type="text" value="0">
        </div>
    </div>

</div>
<script src="{% static 'js/foto_obiecta.js' %}"></script>
{% endblock %}

work/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
  <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
  <link rel="stylesheet" href="{% static 'css/text.css' %}">
  <link rel="stylesheet" href="{% static 'css/product.css' %}">
  <link rel="stylesheet" href="{% static 'css/1_obiect.css' %}">
</head>

<body>
  <header class = "header_conteiner">

      <a href=  /universal-stroyspb/ class="header-logo">
          <img src= "{%static 'img/logo.jpg' %}" class="header-logo">
      </a>
      <div class = "header_conteiner_1">
        <a href="tel:+78129151008" class="header-tel">
          +7(812)915-10-08
        </a>
        <a href="tel:+78129733904" class="header-tel">
          +7(812)973-39-04
        </a>
        <p class="feedcall">
          или
          <a href="#" class="call">оставте номер</a>
          <br>
          и мы вам перезвоним
        </p>
      </div>
      <div class="header_conteiner_2">
        <ul class="main_menu flex">
          <li class = "parant_product_active_1">
            <button class = "parant_product_btn">
              Продукция
            </button>
              <ul class = "dother_menu">
                <li class="dother_product_1">
                    <a href = /universal-stroyspb/bitovki/ class = "dother_product"> Бытовки</a>
                </li>
                <li class="dother_product_1">
                    <a href = /universal-stroyspb/conteineri/ class = "dother_product"> Блок-контейнеры</a>
                </li>
                <li class="dother_product_1">
                    <a href = /universal-stroyspb/modulstr/ class = "dother_product"> Модульные здания</a>
                </li>
                <li class="dother_product_1 ">
                    <a href = /universal-stroyspb/postsec/ class = "dother_product "> Посты охраны</a>
                </li>
                <li class="dother_product_1 last">
                  <a href = /universal-stroyspb/bani/ class = "dother_product last"> Бани </a>
              </li>
              </ul>
            </li>
            <li class = "parant_product_active_1">
            <button class = "parant_product_btn">
              Аренда и Спецпредложения
            </button>
            <ul class = "dother_menu">
              <li class="dother_product_1">
                    <a href = /universal-stroyspb/arenda/ class = "dother_product"> Аренда</a>
                </li>
                <li class="dother_product_1 last">
                    <a href = /universal-stroyspb/sale/ class = "dother_product last"> Спецпредложения</a>
                </li>
              </ul>
            </li>
            <li class = "parant_product_active_1">
            <button class = "parant_product_btn">
              О компании
            </button>
            <ul class = "dother_menu">
              <li class="dother_product_1">
                    <a href = /universal-stroyspb/compania/ class = "dother_product"> О компании</a>
                </li>
                <li class="dother_product_1">
                    <a href = /universal-stroyspb/work/ class = "dother_product"> Наши работы</a>
                </li>
                  <li class="dother_product_1 last">
                    <a href = /universal-stroyspb/garantii/ class = "dother_product last"> Гарантии</a>
                </li>
              </ul>
            </li>
            <li class = "parant_product_active_2">
              <a href = /universal-stroyspb/contaсts/  class = "parant_product_active" href="#">Контакты</a>
            </li>
            <li class = "parant_product_active_1">
              <button class = "parant_product_btn">
                Дополнительно
              </button>
              <ul class = "dother_menu">
                <li class="dother_product_1">
                      <a href = /universal-stroyspb/dostavka/ class = "dother_product"> Доставка</a>
                  </li>
                  <li class="dother_product_1">
                      <a href = /universal-stroyspb/news/ class = "dother_product">Статьи</a>
                  </li>
                    <!-- <li class="dother_product_1 last">
                      <a href = # class = "dother_product last"> Цвета Ral</a>
                  </li> -->
                </ul>
              </li>
        </ul>
      </div>
  </header>

  <div class = conteiner>
    {%  block content %}
    {% endblock %}
  </div>


  <footer class = "footer ">
    <div class="footer_left">
      <p>Контакты</p>
      <ul class="footer_contacts">
        <li class = "footer_contacts_item">
          <p>Телефоны:</p>
          <a href="tel:+78129151008" class="footrer-tel flex">
              +7(812)915-10-08
          </a>
          <a href="tel:+78129733904" class="footer-tel flex">
              +7(812)973-39-04
          </a>
        </li>
        <li  class = "footer_contacts_item">
          <p>Почта:</p>
          <a href=# class="footer-mail flex">
              saddda@mail.ru
          </a>
          <a href=# class="footer-mail flex">
              dasd@mail.ru
          </a>
        </li>
      </ul>
      <div class = "footer_adress flex">
        Санкт-Петербург,
        Карпатская ул. д.14, кор.3., м.Купчино
      </div>
    </div>
    <div class="footer_right">
      <img src=" {% static 'img/logo_footer.jpg' %}" class = "footer_logo">
    </div>
  </footer>
  <script src="{% static 'js/java_script.js' %}"></script>
  <script src="{% static 'js/bitovki.js' %}"></script>

</body>
</html>

work/templates/contact.html
{% extends "base.html" %}
{%  block content %}
{% load static %}

<section class = "left_path">
    <div class = "block">
        <h1>КОНТАКТЫ УНИВЕРСАЛ СТРОЙ</h1>
        <h2>Выставочная площадка:</h2>
        <p>
            Вы можете посмотреть бытовки, блок-контейнеры, бани, посты охраны нашего производства на выставочной площадке в СПб в Купчино.
Адрес: г. Санкт-Петербург, ул. Карпатская д. 14, корп. 3, район Купчино.</p>
<p><b>Телефон:</b>(812) 773-82-85, 915-10-08, 973-39-04</p>
<p><b>e-mail: </b>s9151008@yandex.ru</p>
<p><b>WhatsApp:</b>  +79219151008</p>

<h3>График работы в рабочие дни</h3>

<p>Выставочная площадка открыта для просмотра деревянных бытовок , блок-контейнеров, бань, дома с понедельника по пятницу: 09.00 - 17.00.
        </p>
        <h2>Отдел продаж:</h2>
        <p>
            Понедельник - Пятница 9.00 - 17.00
Суббота и Воскресенье - выходные.

График работы в выходные и праздничные дни

В субботу офис работает по предварительной договорённости.
        </p>
        <h2>
            Кaк добраться общественным транспортом:
        </h2>
        <p>
            От метро «Купчино» автобус № 96, либо маршрутное такси № 383 или №96. Доехать до перекрестка Олеко Дундича и Малая Карпатская. Пройти 100 метров через пустырь до ул. Карпатская. Пройти прямо 100 метров по грунтовой дороге и перед вторым железнодорожным переездом повернуть направо, дойти до середины здания до желтой вывески ООО «Универсал-Строй», офис расположен на 3 этаже.

Если Вы поедете на маршрутном такси №383, то конечная остановка будет перекресток Олеко Дундича и Малая Карпатская.
        </p>
        <h2>Как добраться на машине:</h2>
        <p>
            Два варианта заезда.

1. Заезд с Софийской ул. "между домами 93 и 95". Повернуть направо на Полевую ул., проехать первый ж/д переезд и за ним повернуть налево, доехать до середины здания. Вывеска ООО «Универсал-Строй». Офис расположен на 3 этаже.

2. Заезд на Карпатскую улицу осуществляется с Дунайского проспекта, напротив «Максидома», с Складского проезда и с Грузового проезда. Повернув на Карпатскую улицу, ехать прямо один километр, с левой стороны будет ангар «шина ру» с правой - открытая автостоянка. Нужно повернуть налево перед «шина ру», и за вторым ж/д переездом - направо, доехать до середины здания. Вывеска ООО «Универсал-Строй». Офис расположен на 3 этаже.
        </p>
    </div>
</section>
<section class = "right_path flex">
     <!-- <div> -->
      <!-- <p> Отзывы</p> -->
      <!-- <div class=" sale_1 flex">
        {% for product_img in by_img %}
          <div class ="sale fade" >
            <img src="{{product_img.image}}" class="sale_img" >
            <p class = name_sale>{{product_img.name.name}}</p>
            <p class = old_sale>{{product_img.name.old_price}}</p>
            <p class = price_sale>{{product_img.name.new_price}}</p>
          </div>
        {% endfor %}
      </div>
      <a class="prev" onclick="plusSlide(-1)">&#10094</a>
      <a class="next" onclick="plusSlide(+1)">&#10095</a>
      <div>
        {% for product_img in by_img %}
        <span class = dot></span>
        {% endfor %}
      </div>
    </div>
    <div class = "reviews"> -->
    <!-- </div>  -->
  </section>
  {% endblock %}

work/templates/test.html
<style>
    02
    form[name="form"]{float:left;border:1px solid #ccc;padding:10px;margin-right:5px;}
    03
    input[name="price"]{border:0;}
    04
    </style>
    05
     
    06
    <form name="form">
    07
        <input type="radio" name="check" value="267"><label>200</label>
    08
        <input type="radio" name="check" value="879"><label>500</label>
    09
        <input type="radio" name="check" value="1245"><label>1000</label><br>
    10
        <label>Цена: </label><input type="text" name="price" value="" readonly>
    11
    </form>
    12
     
    13
    <form name="form">
    14
        <input type="radio" name="check" value="267"><label>200</label>
    15
        <input type="radio" name="check" value="879"><label>500</label>
    16
        <input type="radio" name="check" value="1245"><label>1000</label><br>
    17
        <label>Цена: </label><input type="text" name="price" value="" readonly>
    18
    </form>
    19
     
    20
    <form name="form">
    21
        <input type="radio" name="check" value="267"><label>200</label>
    22
        <input type="radio" name="check" value="879"><label>500</label>
    23
        <input type="radio" name="check" value="1245"><label>1000</label><br>
    24
        <label>Цена: </label><input type="text" name="price" value="" readonly>
    25
    </form>
    26
     
    27
    <script>
    28
    for (var i = 0; i < document.form.length; i++) {
    29
        document.form[i].check[0].checked = true;
    30
        document.form[i].price.value = document.form[i].check[0].value;
    31
        document.form[i].onclick = function(e) {
    32
            var target = e && e.target || event.srcElement;
    33
            if (target.name != 'check') return;
    34
            this.price.value = target.value;
    35
        }
    36
    }
    37
    </script>
    